# Comprehensive Pre-flight Validation
# Implements Experiment 1: Pre-Flight Test Environment Validation
#
# This script calls the Python pre_flight_check.py module with all required checks

param(
    [Parameter(Mandatory = $true)]
    [string]$ReplayRoot,

    [Parameter(Mandatory = $true)]
    [string]$Worktree,

    [string]$MavenSettings = 'D:\maven\settings\settings.xml',

    [string]$RootPom = '',

    [string]$OracleBranch = '',

    [int]$TimeoutSeconds = 300
)

$ErrorActionPreference = 'Stop'

function Resolve-AbsolutePath {
    param([string]$Path)
    return [System.IO.Path]::GetFullPath($Path)
}

$replayRootFull = Resolve-AbsolutePath $ReplayRoot
$worktreeFull = Resolve-AbsolutePath $Worktree

# Determine root POM if not specified
if ([string]::IsNullOrWhiteSpace($RootPom)) {
    $RootPom = Join-Path $worktreeFull 'pom.xml'
}

# Build config for Python script
$config = @{
    worktree = $worktreeFull
    maven_settings = $MavenSettings
    root_pom = $RootPom
    oracle_branch = $OracleBranch
} | ConvertTo-Json -Depth 3

# Locate the Python script
$scriptDir = Split-Path -Parent $PSCommandPath
$pythonScript = Join-Path $scriptDir 'pre_flight_check.py'

if (-not (Test-Path -LiteralPath $pythonScript)) {
    throw "Python script not found: $pythonScript"
}

# Run the Python pre-flight check
$env:PYTHONIOENCODING = 'utf-8'
$tempConfig = [System.IO.Path]::GetTempFileName()
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($tempConfig, $config, $utf8NoBom)
$resultJson = & python $pythonScript --config $tempConfig 2>&1
$exitCode = $LASTEXITCODE
Remove-Item -LiteralPath $tempConfig -Force -ErrorAction SilentlyContinue

# Parse result
try {
    $result = ($resultJson -join "`n") | ConvertFrom-Json
} catch {
    $result = [pscustomobject]@{
        overall_status = 'failed'
        checks = @([pscustomobject]@{
            check = 'preflight_wrapper'
            result = 'failed'
            details = "Unable to parse preflight JSON: $($_.Exception.Message). Raw output: $($resultJson -join ' ')"
        })
        failed_count = 1
        warning_count = 0
        recommendation = 'STOP_AND_FIX_PREFLIGHT_WRAPPER'
        phase0_status = 'BLOCKED_PRE_FLIGHT'
    }
}

# Write result to file
$resultPath = Join-Path $replayRootFull 'PREFLIGHT_COMPREHENSIVE.json'
$result | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $resultPath -Encoding UTF8

# Write human-readable blocker if failed
if ($result.overall_status -eq 'failed') {
    $blockerPath = Join-Path $replayRootFull 'PREFLIGHT_BLOCKER.md'

    $failedChecks = $result.checks | Where-Object { $_.result -eq 'failed' }
    $issueList = ($failedChecks | ForEach-Object {
        "- [$($_.check)] $($_.details)"
    }) -join "`n"

    @"
# Comprehensive Pre-flight Blocker

Pre-flight validation failed. Phase 1 implementation must not start.

## Recommendation

**$($result.recommendation)**

## Failed Checks

$issueList

## Decision

BLOCKED - Fix the environment issues before proceeding.

## Recovery Actions

$($result.checks | Where-Object { $_.result -eq 'failed' } | ForEach-Object {
    $action = switch ($_.check) {
        'test_compilation' { 'Fix test compilation errors' }
        'test_harness_dependency' { 'Use an existing test-enabled module such as example-server; do not add JUnit to example-core/pom.xml' }
        'existing_test_errors' { 'Fix existing test errors in example-server' }
        'oracle_accessibility' { 'Verify oracle branch exists and is accessible' }
        default { 'Review and fix the issue' }
    }
    "- $($_.check): $action"
} -join "`n")

---

**Generated by**: Invoke-PreflightComprehensive.ps1
**Exit code**: $exitCode
"@ | Set-Content -LiteralPath $blockerPath -Encoding UTF8

    Write-Host "Preflight: BLOCKED - $($result.failed_count) checks failed"
    exit 1
}

Write-Host "Preflight: PASS - All checks passed"
Write-Host "  Warnings: $($result.warning_count)"

exit 0
